#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
from easygui import *

'''Getting user information through easygui'''
videoFile = fileopenbox("Inform the file to be converted: ", default='*',filetypes = ["*.avi", "*.asf", "*.mov", "*.mp4", "*.m4v", "*.flv", "*.swf", "*.mpg", "*.wmv", "*.mkv", "*.3g2", "*.3gp", "*.mpeg", "*.rm", "*.rmvb", "*.vob", "*.mxf"] , multiple=False).replace(' ', '\ ')
subtitleFile = fileopenbox("Inform the ASS subtitle file: ", default='*',filetypes = ["*.ass"]).replace(' ', '\ ')
convertedFile = filesavebox("Type Converted File Name: ", "Type Converted File Name: ", default='', filetypes= ["*.mov", "*.mp4", "*.m4v"]).replace(' ', '\ ')
convertTo = ' -c:v prores -profile:v 1 -c:a copy -vf subtitles='
extension = '.mov'
'''Treating missing file:'''
if videoFile == '' or subtitleFile == '' or convertedFile == '':
    msgbox("Empty data received when obtaining necessary files!")

'''conversion line:'''
os.system('ffmpeg -i ' + videoFile + convertTo + subtitleFile + ' ' + convertedFile + '-com\ legenda' + extension)
