#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import csv
import os
import sys

def escreveArquivoJson(plataforma, linha):
    file.write('\t\t"PLATAFORMA": "' + str(plataforma) + '",\n')
    file.write('\t\tid: "' + str(data[linha]) + '"\n')

def adicionaPlataforma(col, plat, ln):
    if data[col].upper() == 'Y':
        if col != 1:
            file.write(',\n')
        file.write('\t{\n')
        escreveArquivoJson(plat, ln)
        file.write('\t}')

csvFile = str(sys.argv[1])
os.system('sed 1,1d ' + csvFile + ' >> temp.csv && mv temp.csv ' + csvFile + '')
f = open(csvFile)
csv_f = csv.reader(f)
for row in csv_f:
    data = row
    file = open('contratos.json','a')
    file.write('{\n')
    file.write('\t"' + 'CODIGO INTERNO": ' + str(data[0]) + ',\n')
    file.write('\t"PLATAFORMAS": [\n')
    adicionaPlataforma(1,"now", 2)
    adicionaPlataforma(3,"itunes", 4)
    adicionaPlataforma(5,"amazon", 6)
    adicionaPlataforma(7,"revry", 8)
    adicionaPlataforma(9,"kanopy", 10)
    adicionaPlataforma(11,"alexander street press", 12)
    adicionaPlataforma(13,"vimeo", 14)
    adicionaPlataforma(15,"netflix", 16)
    file.write('\n\t],\n')
    file.write('\t"PERCENTUAL FORNECEDOR": ' + str(data[17]) + ',\n')
    file.write('\t"CONDECINE": ' + str(data[18]) + '\n')
    file.write('}\n')
