#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import csv
import os
import sys

pracas = ''
janelas = ''

csvFile = str(sys.argv[1])
os.system('sed 1,1d ' + csvFile + ' >> temp.csv && mv temp.csv ' + csvFile + '')
f = open(csvFile)
csv_f = csv.reader(f)
for row in csv_f:
    data = row
    pracas = pracas + '\t{\n\t\t"PRAÇA": "' + str(data[0]) + '",\n\t\t"TAXA IMPOSTO": ' + str(data[1]) + '\n\t},\n'
    for i in range(2,31,2):
        janelas = janelas + '\t{\n\t\t"JANELA": "' + str(data[i]) + '",\n\t\t"SHARE": ' + str(data[i+1]) + '\n\t},\n'
pracas = '\t"PRAÇAS" : [\n' + pracas + '\n\t],\n'
janelas = '\t"JANELAS": [\n' + janelas + '\n\t]\n'
arquivoJson = '{\n\t"PLATAFORMA": "now",\n' + pracas + janelas + '\t}\n}\n'
file = open('plataforma.json','a')
file.write(arquivoJson)
