#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
from easygui import *

'''Getting user information through easygui'''
dcpVideoFile = fileopenbox("Inform the DCP Video File: ").replace(' ', '\ ')
dcpAudioFile = fileopenbox("Inform the DCP Audio File: ").replace(' ', '\ ')
choices = ["Full Size (100% of DCP original dimensions)", "Half Size (50% of DCP original dimensions)", "Ultra Low Res (25% of DCP original dimensions)"]
convertTo = choicebox("Reproduction dimensions", "Reproduction dimensions", choices).replace("Full Size (100% of DCP original dimensions)", "0").replace("Half Size (50% of DCP original dimensions)", "1").replace("Ultra Low Res (25% of DCP original dimensions)", "2")

'''Treating missing file:'''
if dcpVideoFile == '' or dcpAudioFile == '':
    msgbox("Empty data received when obtaining necessary files!")

'''conversion line:'''
os.system('ffmpeg -lowres ' + str(convertTo) + ' -ss 0 -i ' + str(dcpVideoFile) + ' -ss 0 -i ' + str(dcpAudioFile) + ' -ac: 2 -c:v mpeg2video -f avi - | ffplay -')
